[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/admin-login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200
